create table Base(
	`IsActive` boolean,
	`Sr.No.` int,
	`Associate ID` varchar(10),
	`Associate Name` varchar(100),
	`Grade HR` varchar(50),
	`On/Off` varchar(10),
	`Home Manager ID` varchar(10),
	`Associate Dept` varchar(100),
    `HCM Name` varchar(100),
    `HCM Dept` varchar(100),
    `Area` varchar(100),
    `Leader` varchar(100),
    `SGA` varchar(3),
    `FTE` float(2),
    `Cost for SGA` float,
    `Current Status for SGA` varchar(100),
	`Project ID` varchar(100),
	`Project Description` varchar(250),
	`Percent Allocation` tinyint,
	`Assignment Start Date`	varchar(15),
    `Date of Joining` varchar(15),
	`FIN Department ID` varchar(10),
	`Department Name` varchar(100),
	`Project Billability` varchar(100),
	`Project Type` varchar(100),
	`Project Status` varchar(100),
	`Project_Solution_Type` varchar(100),
	`Project Manager ID` varchar(10),
	`Project Manager Name` varchar(100),
	`Account ID` varchar(100),
	`Account Name` varchar(100),
	`Parent Customer` varchar(100),
	`Pool ID` int,
	`Pool Description` varchar(250),
	`JobCode` varchar(100),
	`Designation` varchar(100),
	`Grade` char(2),
	`Associate Base Hiring Location` varchar(100),
	`HCM SetID` varchar(5),
	`Project Owning Department` varchar(100),
	`Project Owning Practice` varchar(100),
	`Vertical` varchar(100),
	`Billability Status` char(2),
	`Primary State Tag` varchar(100),
	`Assignment ID` varchar(100),
	`SO ID`	varchar(100),
    `SO Line` int,
	`Critical Flag` varchar(100),
	`Location ID` varchar(100),
	`SEZ Flag` varchar(100),
	`Country` varchar(100),
	`State` varchar(100),
	`City` varchar(100),
	`Assignment End Date` varchar(15),
	`Assignment Status` char(1),
	`Project Role` varchar(100),
	`Operational Role` varchar(100),
	`Assignment location` varchar(100),
	`Assgn City` varchar(100),
	`Assgn State` varchar(100),
	`Assgn Country` varchar(100),
	`Location Reason code` varchar(100),
	`Project Start Date` varchar(15),
	`Project End Date` varchar(15),
	`Sub Vertical` varchar(100),
	`SBU1` varchar(100),
	`SBU2` varchar(100),
	`Contractor End Date` varchar(15),
	`Comment` varchar(250),
	`Pool Resource` char(1),
	`Competency` varchar(100),
	`Secondary State Tag` varchar(100),
	`Replaced Employee` varchar(100),
	`Comments` varchar(250),
	`Client Facility` varchar(100)
);